### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by nathany** [howeyc/fsnotify#78]
## os/fsnotify

It looks like os/fsnotify will take the minimal approach that is appropriate for the os package. It's a good move, especially given the Go 1.3 timeline.
- [x] Merge open pull requests? @howeyc 
- [x] Update code.google.com/p/go.exp/fsnotify to match GitHub master. https://codereview.appspot.com/58500043
- [x] Encourage people to  move issues to https://code.google.com/p/go/issues/list?q=fsnotify
- [ ] Finish API doc http://goo.gl/MrYxyA.
- [x] Modify go.exp/fsnotify to match the proposed os/fsnotify API -- for use in Go 1.2.
- [x] Leave howeyc/fsnotify as-is for existing users.
- [x] Update contributing to get involved with os/fsnotify. #84

I'm not sure what approach @rsc wants to take to get `os/fsnotify` itself implemented.
- [ ] Refactoring, documentation, tests, bugfixing.
- [ ] Close outstanding issues #67, #70, #52 and #7 (perhaps copy relevant issues to https://code.google.com/p/go/issues/list?q=fsnotify). Maybe #79 will help with #62.
